// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(signalRContext))]
    [Migration("20240804195447_restTableStatusUpdate")]
    partial class restTableStatusUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityLayer.Entities.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSelected")
                        .HasColumnType("bit");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            AboutId = 1,
                            Description = "Büyüyen ve gelişen restoran zincirimiz sizlerin desteği ve profesyonel ekibimizin sayesinde yeni şubeler açmaya devam ediyor. İstanbul a yolunuz düşerse aynı lezzeti İstanbul şubemizde de yaşayın, yaşattırın...",
                            ImgUrl = "/images/aboutimages/about2.png",
                            Title = "Lezzet almanı mutluluk kaynağımız...",
                            isSelected = false
                        },
                        new
                        {
                            AboutId = 2,
                            Description = "Lezzet yolculuğunu unutulmaz kılan bir mola arıyorsanız, doğru adrestesiniz. Restoranımız, deneyimli şeflerimizin elinden çıkan benzersiz lezzetlerle dolu bir gastronomi deneyimi sunuyor. Her bir tabak, özenle seçilmiş malzemelerle hazırlanırken, zengin tatlar ve estetik sunumlarla buluşuyor. Misafirperverliğimiz ve kaliteli hizmet anlayışımızla, her ziyaretinizi özel kılmak için buradayız.",
                            ImgUrl = "/images/aboutimages/about-img.png",
                            Title = "Restorantımıza hoşgeldiniz...",
                            isSelected = true
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Basket", b =>
                {
                    b.Property<int>("BasketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BasketId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantTableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BasketId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RestaurantTableId");

                    b.ToTable("Baskets");

                    b.HasData(
                        new
                        {
                            BasketId = 1,
                            Count = 2,
                            Price = 2m,
                            ProductId = 3,
                            RestaurantTableId = 4,
                            TotalPrice = 4m
                        },
                        new
                        {
                            BasketId = 2,
                            Count = 1,
                            Price = 85m,
                            ProductId = 5,
                            RestaurantTableId = 4,
                            TotalPrice = 85m
                        },
                        new
                        {
                            BasketId = 3,
                            Count = 1,
                            Price = 120m,
                            ProductId = 10,
                            RestaurantTableId = 4,
                            TotalPrice = 120m
                        },
                        new
                        {
                            BasketId = 4,
                            Count = 1,
                            Price = 15m,
                            ProductId = 2,
                            RestaurantTableId = 4,
                            TotalPrice = 15m
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfCustomers")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Mustafa Çilekçi",
                            Email = "mcilekci@gmail.com",
                            NumberOfCustomers = 4,
                            Phone = "0543 123 1122",
                            Status = 0
                        },
                        new
                        {
                            BookingId = 2,
                            BookingDate = new DateTime(2024, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Naz Farklı",
                            Email = "nazfarkli@gmail.com",
                            NumberOfCustomers = 2,
                            Phone = "0555 123 1144",
                            Status = 1
                        },
                        new
                        {
                            BookingId = 3,
                            BookingDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Altan Kemal Özden",
                            Email = "altankemal@gmail.com",
                            NumberOfCustomers = 5,
                            Phone = "0507 123 5533",
                            Status = 2
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Hamburger",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Makarna",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "İçecek",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Salata",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Balık",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Pizza",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Kızartma",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Vejeteryan",
                            Status = false
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isSelected")
                        .HasColumnType("bit");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Email = "restorankonyasube@gmail.com",
                            Location = "Konya",
                            Phone = "0543 789 01 23",
                            isSelected = false
                        },
                        new
                        {
                            ContactId = 2,
                            Email = "restoranizmirsube@gmail.com",
                            Location = "İzmir",
                            Phone = "0543 555 66 77",
                            isSelected = false
                        },
                        new
                        {
                            ContactId = 3,
                            Email = "restoranistanbulsube@gmail.com",
                            Location = "İstanbul",
                            Phone = "0543 888 88 99",
                            isSelected = false
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.ContactFormMessage", b =>
                {
                    b.Property<int>("ContactFormMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactFormMessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactFormMessageId");

                    b.ToTable("ContactFormMessages");

                    b.HasData(
                        new
                        {
                            ContactFormMessageId = 1,
                            Content = "Merhaba, restoranınızı uzun zamandır duyuyorum ve ilk kez ziyaret etmek istiyorum. Menünüzde vejeteryan yemek göremedim, acaba özel olarak yaptığınız menüde bulunmaya bir vejeteryan yemeğiniz var mıydı?",
                            Date = new DateTime(2024, 7, 15, 23, 28, 5, 0, DateTimeKind.Unspecified),
                            IsRead = true,
                            Mail = "mpekmez@yandex.com",
                            NameSurname = "Mustafa Pekmez",
                            Phone = "0554 454 55 66",
                            Title = "Vejeteryan menü var mı"
                        },
                        new
                        {
                            ContactFormMessageId = 2,
                            Content = "Merhaba, çocuk menünüz ve çocuk sandalyeniz var mıydı acaba?",
                            Date = new DateTime(2024, 1, 8, 5, 26, 43, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Mail = "handeyet@gmail.com",
                            NameSurname = "Hande Yetkin",
                            Phone = "0554 555 77 56",
                            Title = "Çocuk menüsü"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.CustomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.CustomUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.DiscountedProduct", b =>
                {
                    b.Property<int>("DiscountedProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountedProductId"));

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("DiscountedProductId");

                    b.ToTable("DiscountedProducts");

                    b.HasData(
                        new
                        {
                            DiscountedProductId = 1,
                            DiscountRate = 20,
                            ImgUrl = "/images/discountedproductsimages/o1.jpg",
                            Title = "Tadımıza Tat Katalım",
                            isActive = false
                        },
                        new
                        {
                            DiscountedProductId = 2,
                            DiscountRate = 15,
                            ImgUrl = "/images/discountedproductsimages/o2.jpg",
                            Title = "Haftanın Lezzeti",
                            isActive = false
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            Text = "Restoranımızın mutfağında çalışan şeflerimiz, lezzetin sınırlarını zorlayan yaratıcı tarifleriyle tanınıyor. Her biri alanında uzmanlaşmış olan şeflerimiz, en taze ve yerel malzemeleri kullanarak unutulmaz tatlar sunuyor.",
                            Title = "Deneyimli Şeflerden Oluşan Mutfak Ekibi"
                        },
                        new
                        {
                            FeatureId = 2,
                            Text = "Misafirlerimize modern ve zarif bir atmosferde hizmet veriyoruz. Restoranımızın sunduğu şehir manzarası eşliğinde, keyifli bir yemek deneyimi yaşayabilirsiniz. Her detayı özenle tasarlanmış dekorasyonumuz, konforunuz için özel olarak düşünüldü.",
                            Title = "Şık ve Şehir Manzaralı Atmosfer"
                        },
                        new
                        {
                            FeatureId = 3,
                            Text = "Çevre dostu bir yaklaşımla hareket ediyoruz ve sürdürülebilirlik ilkelerine önem veriyoruz. Menümüzde yer alan ürünlerin büyük çoğunluğu yerel tedarikçilerden temin edilirken, doğal ve organik ürünleri tercih ediyoruz. Bu sayede hem sağlığınıza hem de çevreye katkıda bulunuyoruz.",
                            Title = "Sürdürülebilirlik ve Yerel Ürünler"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.FooterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FooterInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Restoranımızda lezzet ve misafirperverlik buluşuyor. Modern ve şık atmosferimizde, yaratıcı şeflerimizin hazırladığı özenli yemeklerle unutulmaz bir deneyim yaşayın.",
                            IsActive = true,
                            Title = "Lezzeti Yaşayın"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tam bir lezzet fabrikası olan restoranımızdan sevdiklerinizin de faydalanması bizlerin de mutluluğu olur.",
                            IsActive = false,
                            Title = "Tadın, Tattırın"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.MoneyBox", b =>
                {
                    b.Property<int>("MoneyBoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MoneyBoxId"));

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MoneyBoxId");

                    b.ToTable("MoneyBoxes");

                    b.HasData(
                        new
                        {
                            MoneyBoxId = 1,
                            TotalAmount = 100m
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            Date = new DateTime(2024, 7, 12, 15, 30, 45, 0, DateTimeKind.Unspecified),
                            Description = "Toplantı",
                            IsRead = true,
                            Type = "primary"
                        },
                        new
                        {
                            NotificationId = 2,
                            Date = new DateTime(2024, 8, 4, 16, 52, 32, 0, DateTimeKind.Unspecified),
                            Description = "Prim Ödemeleri",
                            IsRead = true,
                            Type = "warning"
                        },
                        new
                        {
                            NotificationId = 3,
                            Date = new DateTime(2024, 8, 4, 13, 35, 5, 0, DateTimeKind.Unspecified),
                            Description = "Toplantı",
                            IsRead = false,
                            Type = "primary"
                        },
                        new
                        {
                            NotificationId = 4,
                            Date = new DateTime(2024, 8, 4, 14, 15, 45, 0, DateTimeKind.Unspecified),
                            Description = "Denetleme",
                            IsRead = true,
                            Type = "danger"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.OpenHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClosingHour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OpenDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OpenHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosingHour = "21.30",
                            IsActive = true,
                            OpenDays = "Pazartesi-Cumartesi",
                            OpeningHour = "09.00"
                        },
                        new
                        {
                            Id = 2,
                            ClosingHour = "22.00",
                            IsActive = false,
                            OpenDays = "Her Gün",
                            OpeningHour = "09.00"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Description = "Hesap Kapatıldı",
                            OrderDate = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableNumber = "Salon 01",
                            TotalPrice = 0m
                        },
                        new
                        {
                            OrderId = 2,
                            Description = "Hesap Kapatıldı",
                            OrderDate = new DateTime(2024, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableNumber = "Salon 02",
                            TotalPrice = 0m
                        },
                        new
                        {
                            OrderId = 3,
                            Description = "Müşteri Masada",
                            OrderDate = new DateTime(2024, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableNumber = "Salon 03",
                            TotalPrice = 0m
                        },
                        new
                        {
                            OrderId = 4,
                            Description = "Müşteri Masada",
                            OrderDate = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TableNumber = "Bahçe 01",
                            TotalPrice = 0m
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            ProductCount = 2,
                            ProductId = 1,
                            ProductPrice = 5m,
                            TotalPrice = 10m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 1,
                            ProductCount = 1,
                            ProductId = 2,
                            ProductPrice = 7m,
                            TotalPrice = 7m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 2,
                            ProductCount = 3,
                            ProductId = 4,
                            ProductPrice = 12m,
                            TotalPrice = 36m
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProductStatus")
                        .HasColumnType("bit");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            Description = "Spagetti lezzeti",
                            ImgUrl = "/images/productimages/spagetti.png",
                            Price = 60m,
                            ProductName = "Spagetti",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            Description = "Türk markası  kola tercihimiz",
                            ImgUrl = "/images/productimages/colaturca.png",
                            Price = 15m,
                            ProductName = "Cola Turka",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "Erikli 0,5l su",
                            ImgUrl = "/images/productimages/su.png",
                            Price = 2m,
                            ProductName = "Su",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Description = "Akdeniz lezzetlerinin buluştuğu salata",
                            ImgUrl = "/images/productimages/akdenizSalatası.png",
                            Price = 12m,
                            ProductName = "Akdeniz Salatası",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 6,
                            Description = "Nefis 5 farklı çeşit peynirle donanmış pizza",
                            ImgUrl = "/images/productimages/peynirliPizza.png",
                            Price = 85m,
                            ProductName = "Peynirli Pizza",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 6,
                            Description = "Her lezzet dilimin ucunda olsun diyenlere",
                            ImgUrl = "/images/productimages/karışıkPizza.png",
                            Price = 80m,
                            ProductName = "Karışık Pizza",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 6,
                            Description = "Sucuk ve pizzanın muhteşem tadına bayılacaksınız",
                            ImgUrl = "/images/productimages/sucukluPizza.png",
                            Price = 90m,
                            ProductName = "Sucuklu Pizza",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Description = "Doyuracak bir hamburger menü isteyenlere",
                            ImgUrl = "/images/productimages/wooperMenu.png",
                            Price = 70m,
                            ProductName = "Whooper Menü",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            Description = "Ben birazcık fazla mı yesem diyenlere",
                            ImgUrl = "/images/productimages/doubleHamburger.png",
                            Price = 100m,
                            ProductName = "Double Hamburger",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            Description = "Ben doyamam büyük sar abi diyenlere",
                            ImgUrl = "/images/productimages/tripleHamburger.png",
                            Price = 120m,
                            ProductName = "Triple Hamburger",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 5,
                            Description = "Enfes mangalda balık lezzeti damağınızı şenlendirecek",
                            ImgUrl = "/images/productimages/somon.png",
                            Price = 100m,
                            ProductName = "Somon",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Description = "Taze sebzelerle hazırlanan hafif makarnamız",
                            ImgUrl = "/images/productimages/pastaPrimavera.png",
                            Price = 220m,
                            ProductName = "Pasta Primavera",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Description = "Kıvrımlı ve spiral şeklindeki makarnamız.",
                            ImgUrl = "/images/productimages/Cavatappi.png",
                            Price = 220m,
                            ProductName = "Cavatappi",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 7,
                            Description = "İnce dilimlenmiş veya jülyen kesilmiş leziz patateslerimiz",
                            ImgUrl = "/images/productimages/patatesKızartma.png",
                            Price = 50m,
                            ProductName = "Patates Kızartması",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 7,
                            Description = "Baharatlı ve lezzetli soğanlar halkalarımız.",
                            ImgUrl = "/images/productimages/soğanHalkası.png",
                            Price = 65m,
                            ProductName = "Soğan Halkası",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4,
                            Description = "Tapzate sebzelerle klasik ama leziz salatamı.",
                            ImgUrl = "/images/productimages/çobanSalata.png",
                            Price = 50m,
                            ProductName = "Çoban Salata",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 7,
                            Description = "Üzerinde eritilmiş peynir ile tam bir harika.",
                            ImgUrl = "/images/productimages/mantar.png",
                            Price = 45m,
                            ProductName = "Kızarmış Mantar",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 8,
                            Description = "İnce bulgur, domates, salatalık, yeşillikler şöleni.",
                            ImgUrl = "/images/productimages/kısır.png",
                            Price = 85m,
                            ProductName = "Kısır",
                            ProductStatus = true
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 8,
                            Description = "Taze enginarlarımızın zeytinyağı, limon suyu, soğan ve baharatlarla dansı.",
                            ImgUrl = "/images/productimages/enginar.png",
                            Price = 110m,
                            ProductName = "Zeytinyağlı Enginar",
                            ProductStatus = true
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.RestaurantTable", b =>
                {
                    b.Property<int>("RestaurantTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantTableId"));

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestaurantTableId");

                    b.ToTable("RestaurantTables");

                    b.HasData(
                        new
                        {
                            RestaurantTableId = 1,
                            Status = false,
                            TableName = "Masa 1"
                        },
                        new
                        {
                            RestaurantTableId = 2,
                            Status = false,
                            TableName = "Masa 2"
                        },
                        new
                        {
                            RestaurantTableId = 3,
                            Status = false,
                            TableName = "Masa 3"
                        },
                        new
                        {
                            RestaurantTableId = 4,
                            Status = false,
                            TableName = "Masa 4"
                        },
                        new
                        {
                            RestaurantTableId = 5,
                            Status = false,
                            TableName = "Masa 5"
                        },
                        new
                        {
                            RestaurantTableId = 6,
                            Status = false,
                            TableName = "Masa 6"
                        },
                        new
                        {
                            RestaurantTableId = 7,
                            Status = false,
                            TableName = "Bahçe 1"
                        },
                        new
                        {
                            RestaurantTableId = 8,
                            Status = false,
                            TableName = "Bahçe 2"
                        },
                        new
                        {
                            RestaurantTableId = 9,
                            Status = true,
                            TableName = "Bahçe 3"
                        },
                        new
                        {
                            RestaurantTableId = 10,
                            Status = true,
                            TableName = "Bahçe 4"
                        },
                        new
                        {
                            RestaurantTableId = 11,
                            Status = false,
                            TableName = "Bahçe 5"
                        },
                        new
                        {
                            RestaurantTableId = 12,
                            Status = true,
                            TableName = "Bahçe 6"
                        },
                        new
                        {
                            RestaurantTableId = 13,
                            Status = false,
                            TableName = "Teras 1"
                        },
                        new
                        {
                            RestaurantTableId = 14,
                            Status = false,
                            TableName = "Teras 2"
                        },
                        new
                        {
                            RestaurantTableId = 15,
                            Status = false,
                            TableName = "Teras 3"
                        },
                        new
                        {
                            RestaurantTableId = 16,
                            Status = false,
                            TableName = "Teras 4"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.SocialMedia", b =>
                {
                    b.Property<int>("SocialMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialMediaId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialMediaId");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            SocialMediaId = 1,
                            Icon = "fa fa-facebook",
                            IsActive = true,
                            Platform = "facebook",
                            siteUrl = "www.facebook.com"
                        },
                        new
                        {
                            SocialMediaId = 2,
                            Icon = "fa fa-twitter",
                            IsActive = true,
                            Platform = "twitter",
                            siteUrl = "www.twitter.com"
                        },
                        new
                        {
                            SocialMediaId = 3,
                            Icon = "fa fa-linkedin",
                            IsActive = true,
                            Platform = "linkedin",
                            siteUrl = "www.linkedin.com"
                        },
                        new
                        {
                            SocialMediaId = 4,
                            Icon = "fa fa-instagram",
                            IsActive = true,
                            Platform = "instagram",
                            siteUrl = "www.instagram.com"
                        },
                        new
                        {
                            SocialMediaId = 5,
                            Icon = "fa fa-pinterest",
                            IsActive = true,
                            Platform = "pinterest",
                            siteUrl = "www.pinterest.com"
                        },
                        new
                        {
                            SocialMediaId = 6,
                            Icon = "fa fa-youtube",
                            IsActive = true,
                            Platform = "youtube",
                            siteUrl = "www.youtube.com"
                        },
                        new
                        {
                            SocialMediaId = 7,
                            Icon = "fa fa-reddit",
                            IsActive = true,
                            Platform = "reddit",
                            siteUrl = "www.reddit.com"
                        },
                        new
                        {
                            SocialMediaId = 8,
                            Icon = "fa fa-telegram",
                            IsActive = true,
                            Platform = "telegram",
                            siteUrl = "www.telegram.com"
                        },
                        new
                        {
                            SocialMediaId = 9,
                            Icon = "fa fa-whatsapp",
                            IsActive = true,
                            Platform = "whatsapp",
                            siteUrl = "www.whatsapp.com"
                        },
                        new
                        {
                            SocialMediaId = 10,
                            Icon = "fa fa-snapchat",
                            IsActive = true,
                            Platform = "snapchat",
                            siteUrl = "www.snapchat.com"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.Testimonial", b =>
                {
                    b.Property<int>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WriterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestimonialId");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            TestimonialId = 1,
                            Comment = "Restoranınızın atmosferi gerçekten büyüleyici! Yemekler harikaydı, özellikle deniz ürünleri çok taze ve lezzetliydi. Servis hızlı ve personel çok ilgiliydi. Tekrar gelmek için sabırsızlanıyorum.",
                            ImgUrl = "/images/clientimages/k1.jpg",
                            Status = true,
                            Title = "Harika Atmosfer",
                            WriterName = "Ayşe"
                        },
                        new
                        {
                            TestimonialId = 2,
                            Comment = "Geçen hafta burada ailemle birlikte akşam yemeği yedik ve çok memnun kaldık. Yemeklerin lezzeti harikaydı, özellikle şefin önerdiği ana yemek beni çok güzeldi. Hizmet kalitesi ve personelin güleryüzü ise takdire şayan. Kesinlikle tekrar geleceğiz.",
                            ImgUrl = "/images/clientimages/e1.jpg",
                            Status = true,
                            Title = "Mükemmel Hizmet",
                            WriterName = "Mehmet"
                        },
                        new
                        {
                            TestimonialId = 3,
                            Comment = "Restoranınızın sunduğu manzara gerçekten nefes kesici! Özellikle akşamüstü saatlerinde burada oturmak büyük keyif. Yemeklerin lezzeti de çok başarılıydı. Çalışanlarınızın ilgisi ve servis hızı da memnuniyet vericiydi. Herkese tavsiye ederim.",
                            ImgUrl = "/images/clientimages/k2.jpg",
                            Status = true,
                            Title = "Muhteşem Manzara",
                            WriterName = "Fatma"
                        },
                        new
                        {
                            TestimonialId = 4,
                            Comment = "Arkadaşlarımı buraya getirdim ve hepsi çok memnun kaldı. Özellikle tadı damağımızda kalan tatlılar harikaydı. Restoranınızın ambiansı da çok hoştu, sıcak bir ortam sağlıyorsunuz. Teşekkürler!",
                            ImgUrl = "/images/clientimages/e2",
                            Status = true,
                            Title = "Özel Bir Deneyim",
                            WriterName = "Ali"
                        },
                        new
                        {
                            TestimonialId = 5,
                            Comment = "Burada yediğimiz yemekler gerçekten ilham vericiydi. Yaratıcı sunumlar ve lezzetli tatlar bizi etkiledi. Servis çok profesyonel ve sıcak bir karşılama aldık. Herkese öneririm!",
                            ImgUrl = "/images/clientimages/k1.jpg",
                            Status = true,
                            Title = "İlham Verici Yemekler",
                            WriterName = "Zeynep"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EntityLayer.Entities.Basket", b =>
                {
                    b.HasOne("EntityLayer.Entities.Product", "Product")
                        .WithMany("Baskets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.RestaurantTable", "RestaurantTable")
                        .WithMany("Baskets")
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("EntityLayer.Entities.OrderDetail", b =>
                {
                    b.HasOne("EntityLayer.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EntityLayer.Entities.Product", b =>
                {
                    b.HasOne("EntityLayer.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.CustomRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EntityLayer.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("EntityLayer.Entities.Product", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("EntityLayer.Entities.RestaurantTable", b =>
                {
                    b.Navigation("Baskets");
                });
#pragma warning restore 612, 618
        }
    }
}
